version: '3.9'

services:
  backend:
    build: ./backend
    env_file: ".env"
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/run
    restart: always

  frontend:
    build: ./frontend
    container_name: ts_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: always
    command: npm run dev